### ISSUE TITLE
PHP8 Version error

### ISSUE THREAD

**Issue by lahivee** [laravel/forge-cli#12]
- Forge CLI Version: 0.1.5
- PHP Version: 8.0.8

### Description:
I have PHP 8.0.8 installed but the software tells me that it is required PHP 7.3. I checked the composer.json of the package for missing version declaration and noticed there is only one pipe in "^7.3|^8.0". Is this the problem?

![Screen Shot 2021-08-05 at 5 13 57 PM](https://user-images.githubusercontent.com/2931598/128375644-66e63812-d693-4b0e-ae7f-07f89202d141.png)

### Steps To Reproduce:
1. Install PHP 8.0.8 on Mac via Homebrew
2. Install latest forge-cli

**Comment by driesvints** [comment]
Does your app have ^8.0 in its composer.json?

**Comment by lahivee** [comment]
I first had the issue running globally from my home directory, but i now also tested by cd'ing into my app directory and the same issue is present. Yes, the app i cd'ed into has php8 requirement:

![Screen Shot 2021-08-05 at 5 26 44 PM](https://user-images.githubusercontent.com/2931598/128377143-ed5726bb-c827-44b3-b2e4-642dc6726ef0.png)

**Comment by nunomaduro** [comment]
Can you share your global "composer.lock" please?

**Comment by lahivee** [comment]
By looking into the the composer.lock file you mentioned i noticed that i still have the abandoned Forge-Cli package from BeyondCode installed. This seems to have caused the issue and it works now! Thank you for pointing me to this!
