### ISSUE TITLE
Pull in functionality from BeyondCode's predecessor

### ISSUE THREAD

**Issue by lahivee** [laravel/forge-cli#14]
Hi,

I have been using BeyondCodes forge-cli package before and they have 2 very useful features that would definitely enhance this package:
1. Manage environment files (similar to it already exists in Laravel vapor-cli)
2. Syncronize configuration into a forge.yml. This will store the server setup in version control which makes it so much easier to set up new servers, restore the configuration, ... while it is all version controlled. (also similar to Laravel Vapor's vapor.yml)

This is the link to the repository: https://github.com/beyondcode/forge-cli

Is this something that is planned or you are open to add to this CLI package?

**Comment by nunomaduro** [comment]
No plans for the suggestion number 2. Regarding the suggestion number one, we will consider it.
