### ISSUE TITLE
Curl Error. Could not resolve host

### ISSUE THREAD

**Issue by tomsgad** [laravel/forge-cli#15]
- Forge CLI Version: 0.1.5
  - PHP Version: 8.0.2
  - Operating System: WINNT
  - Error Message: cURL error 6: Could not resolve host: forge.laravel.com (s
  ee https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://forge.la
  ravel.com/api/v1/servers/483535.

### Steps To Reproduce:
forge deploy site

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
