### ISSUE TITLE
Save server and site configuration in file

### ISSUE THREAD

**Issue by Iamscaredofcode** [laravel/forge-cli#17]
Is it possible to store the site configuration in the repository?

When I deploy customers sites (this happens often unfortunately) in the company i always have to configure all the fields in the forge interface instead of being able to copy from another project like you can do in vapor for example.

Is this possible or do we have to configure this every time in the forge panel?

Thanks!

**Comment by Iamscaredofcode** [comment]
This also helps when people would like to deploy servers for redundancy, so we don't have to configure all the settings every time we spin up a server

**Comment by Iamscaredofcode** [comment]
Hello Dries, I noticed you added needs-more-info label, so I try to clarify this:

I am not a Vapor user but i remember this feature from when it was released, and when i saw this package I was not sure if this is possible too: https://docs.vapor.build/1.0/projects/environments.html#creating-environments

Basically, you write the environment- or in this case site-settings into a file (vapor.yml). So you can copy it between sites when you setup a new site, or move a site to another server, and also commit it which feels safer and more relatable to me.

Did I miss this feature in this package or does it not exist?

**Comment by nunomaduro** [comment]
No plans to change this - for now.
