### ISSUE TITLE
forge tinker fails to find artisan for none default path

### ISSUE THREAD

**Issue by tobz-nz** [laravel/forge-cli#2]
I have my site setup in `/home/forge/site.name.com/current` which is a symlink to a release folder.
`forge tinker` does not check for this convention.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by tobz-nz** [comment]
ah, I thought it was a bug.
Other commands look in multiple folders often used in the same conventions - eg the log viewer checks in both `storage/logs/...` and `shared/storage/logs/...`. The `shared` folder being shared across releases.
In my case I'm using deployer.org, which the same folder structure.
