### ISSUE TITLE
Use specified SSH key

### ISSUE THREAD

**Issue by nivv** [laravel/forge-cli#22]
Would be nice to be able to use a specific SSH key. We have about 30 servers in our Forge account and it's a bit cumbersome to add a specific Forge CLI key to every server, then multiply that with a couple of developers.

When we provision a new server SSH keys gets added for each developer and then we all can connect without adding the keys manually. Something like this perhaps:

```
$ forge server:current --key=my-key-that-is-added-to-all-servers.pub
```

Maybe I'm missing something, but I've read the docs and couldn't find an override.

Edit:
A thought would be to specify which keys to use in `~/.ssh/config`, but then again, we have a bunch of servers which would make that a bit fiddly

**Comment by nunomaduro** [comment]
When you run `ssh:test` without adding "a specific Forge CLI key", what happens?

**Comment by driesvints** [comment]
@nivv feel free to re-open a new issue if you want.

**Comment by nivv** [comment]
Sorry, missed this notification.

When configuring a new server connection I get these choices (all my ssh keys)
```
 ‣ Which Key Would You Like To Use:
  [0] Create new key
  [1] Reuse some-id.pub
  [2] Reuse me_id.pub
  [3] Reuse gitlab_ci_id.pub
  [4] Reuse id_github.pub
  [5] Reuse id_rsa.pub
 >
```
If I choose any of the above that isn't `id_rsa.pub` the `ssh:test` command will fail.

Say for example that I choose the first key (`some-id.pub`)

```
 ‣ What Should The SSH Key Be Named In Forge [username]:
 > forge-cli-test

==> Adding Key [some-id.pub] With The Name [forge-cli-test] To Server [Purple Pebble]
==> SSH Key Based Secure Authentication Configured Successfully
```

Then I run `ssh:test` I get the error:
```
==> Establishing Secure Connection


  Unable to connect to remote server. Maybe run [ssh:configure] to configure an SSH Key?
```

Somehow forge-cli appears to choose `id_rsa.pub` when connecting with SSH.

**Comment by nunomaduro** [comment]
What happens if you type `ssh forge@YourServerIp`?

**Comment by nivv** [comment]
@nunomaduro 

```
↳ ssh forge@18.195.xxx.xx
forge@18.195.xx.xx: Permission denied (publickey).
```

I think my `ssh`-configuration defaults to a key that is not ` id_rsa.pub`

**Comment by nunomaduro** [comment]
Thank you for explaining. We are going to wait for a few more reports, to validate that this is a "real" issue before actually investigating a little bit more.

**Comment by cursosdesarrolloweb** [comment]
Same issue here, if key file is named to id_rsa all works fine, with another names the command forge ssh fails, but ssh {alias_config} or ssh forge@ip -i .pubfile works fine.
