### ISSUE TITLE
PHP version error while version is >7.3

### ISSUE THREAD

**Issue by drjdr** [laravel/forge-cli#24]
- Forge CLI Version: 1.1 
- PHP Version: 8.0.9 (default brew install on mac m1)

### Description:
$ forge

Box Requirements Checker
========================

> Using PHP 8.0.9
> PHP is using the following php.ini file:
  /opt/homebrew/etc/php/8.0/php.ini

> Checking Box requirements:
  E.

                                                                                
 [ERROR] Your system is not ready to run the application.                       
                                                                                

Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.3" or greater.

### Steps To Reproduce:
Instructions as on forge cli website : composer global install laravel/forge-cli
forge

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by bolechen** [comment]
Can you run "composer global remove beyondcode/forge-cli"
