### ISSUE TITLE
Authenticating forge cli is failing

### ISSUE THREAD

**Issue by hfatahi** [laravel/forge-cli#25]
- Forge CLI Version: 1.1.0
- PHP Version: 7.4.22
- Windows Version: 10 Pro

### Description:
I wanted to give forge-cli a try. I installed it globally, grabbed an api token, then tried `forge login`. I got the following error
![forge-cli-login-error](https://user-images.githubusercontent.com/8626733/130070918-49289454-0d44-4aa8-bcaf-6c6df6ab4d8b.png)

### Steps To Reproduce:
- Install forge-cli globally
- Grab an api token
- Try to login `forge login`

**Comment by driesvints** [comment]
This is a network issue on your end.
