### ISSUE TITLE
Deploy a specific branch from the command line

### ISSUE THREAD

**Issue by rachelv** [laravel/forge-cli#27]
For our very small team's workflow, it would be helpful for anyone to be able to deploy any branch to the test server without needing to update the branch via the Forge web UI.

Something like:
forge deploy example.com feature-branch

This is maybe possible already by first using the Forge SDK and calling $site->updateGitRepository() before deployment, but would be nice to have it bundled in the Forge CLI.

Thanks for considering.

**Comment by nunomaduro** [comment]
I've added this feature to our backlog. If more customers ask for this, we are going to add it.

**Comment by sc-creed** [comment]
This would be pretty useful for me as well.

I apologize if I should have used another method to indicate, 'I'm kindly asking for this too'.

🙂 Thanks!

**Comment by hasfoug** [comment]
Would be very useful to have this! Any chance for this to be added in the nearest future?
