### ISSUE TITLE
Error Message: Trying to access array offset on value of type null. 

### ISSUE THREAD

**Issue by tomcrofty** [laravel/forge-cli#28]
- Forge CLI Version: 1.1.0
- PHP Version: 8.0.3

### Description:

When using `forge ssh:configure` I get an error. After selecting the server, creating a new key and naming it I get `Error Message: Trying to access array offset on value of type null. `

### Steps To Reproduce:
forge ssh:configure
server id
0 (create new key)
ssh key name

Then error shows

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by driesvints** [comment]
Also search this issue tracker because we've been getting a number of reports that were related to improper usage.

**Comment by tomcrofty** [comment]
Just did some digging, the error occurs when VS code is set to the default program to open PHP files, it occurs when keysFactory.php is run. I noticed this as that file would randomly open in VS code when using `ssh:configure`.

Not sure of an instant fix but there's likely a way to execute that file with PHP.exe and not just whatever the default .php handler is for the OS.

**Comment by tomcrofty** [comment]
https://stackoverflow.com/questions/66285746/why-does-exec-open-a-file-instead-of-execute-it
