### ISSUE TITLE
Unspecific error message after branch name change

### ISSUE THREAD

**Issue by lasseeee** [laravel/forge-cli#29]
- Forge CLI Version: 1.1.0
- PHP Version: 7.4.20

### Description:

```
An unexpected error occured. Please report this issue here:
  https://github.com/laravel/forge-cli/issues/new/choose

  - Forge CLI Version: 1.1.0
  - PHP Version: 7.4.20
  - Operating System: Darwin
  - Error Message: Failed to deploy. Please refresh the tokens in your Forge profile..
```

### Steps To Reproduce:

Change the branch name on Github without updating the branch name at Forge, then try to deploy. The error message could if possible be more specific rather than `Please refresh the tokens in your Forge profile..`.

**Comment by nunomaduro** [comment]
You are right. We are going to address this on the Forge API side.
