### ISSUE TITLE
[ERROR] Your system is not ready to run the application.

### ISSUE THREAD

**Issue by mathiaspalmqvist** [laravel/forge-cli#47]
- Forge CLI Version: 1.3.4
- PHP Version: 8.0.6
- MacOs: 12.0
- Processor: M1 Pro

### Description:
I am trying to run Forge CLI but get an error message that I am not running a higher version than PHP 7.3 but I'm running it with PHP 8.0.6.

```
Box Requirements Checker
========================

> Using PHP 8.0.6
> PHP is using the following php.ini file:
  /usr/local/etc/php/8.0/php.ini

> Checking Box requirements:
  E.

                                                                                
 [ERROR] Your system is not ready to run the application.                       
                                                                                

Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.3" or greater.
```

### Steps To Reproduce:
1. Open Terminal
2. Run command: forge

**Comment by nunomaduro** [comment]
Can you run "composer global remove beyondcode/forge-cli"? Seem people are still using that package that conflicts with this one.

**Comment by mathiaspalmqvist** [comment]
Thank you, that did the trick 👍

**Comment by nunomaduro** [comment]
cc @driesvints In case in see this in the future.
