### ISSUE TITLE
possible to clone site/server configuration? + idea

### ISSUE THREAD

**Issue by lahivee** [laravel/forge-cli#49]
i am managing a lot of sites (20+) on many servers and i find it a huge effort to manage my servers from the forge web dashboard.

this means that there are basically `(20 + server amount) * configuration sections` different configuration pages in forge that need to be configured which is huge and hard to manage.

i also often need to clone a site (and server) for clients and i did not find a clone server/site option in forge. (maybe i missed it?)

so to fix this problem i thought of a better way to solve this: introduce .toml configuration files

this would basically solve all these issues because:
1. you have a single file that contains all configuration (so you dont need to switch between sites and tabs all the time)
2. they can easily be copied to new codebases which makes it easy to clone sites/servers
3. they are version controlled so you have a history of all changes
4. if you have employees you can make sure for configuration changes to be reviewed via a pull request
5. maybe even more benefits i have not thought of

let me know what you think and if something like file-based configurations have been considered :)

**Comment by nunomaduro** [comment]
We are going to discuss your suggestion internally. Thank you for proposing this.

**Comment by brentdodell** [comment]
@nunomaduro, what came of the conversation? I'm exploring tools for server management (specifically for Wordpress, though I'd be interested in a tool that worked for other technologies as well). One of my requirements is the ability to clone sites.
