### ISSUE TITLE
Curl Error on Windows Environments

### ISSUE THREAD

**Issue by geisi** [laravel/forge-cli#5]
Hello,

on Windows Environments (whos using Windows wtf?) tested on two different machines
PHP 8.x installed per chocolatey package manager Curl errors occure on every Forge Curl Request.

```
In CurlFactory.php line 211:

  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.htm
  l) for https://forge.laravel.com/api/v1/user
```

To fix this error you have to configure the curl pem certificates in your php.ini
https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

Im no curl expert but maybe the requests have to be started with different params or the root certificate can be integrated into the cli ?

Windows Build Number:
21H1 19043.1110

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by umaraziz0** [comment]
> To fix this error you have to configure the curl pem certificates in your php.ini [stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate](https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate)

Had the same exact issue, got mine working because of this fix. Thanks!

**Comment by Stan-l-e-y** [comment]
> Also had the same error, thank you!
