### ISSUE TITLE
Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by briantuju** [laravel/forge-cli#53]
- Forge CLI Version: 1.3.4
- PHP Version: 8.1.2

### Description:
I am experiencing an error when I try to view my site logs via the CLI. 
I have authenticated properly, and the SSH is working too.
The error message I'm getting is `strtolower(): Passing null to parameter #1 ($string) of type string is deprecated.`

### Steps To Reproduce:
Run the command to list site logs:
`forge site:logs [my_site_name.com]`

**Comment by nunomaduro** [comment]
@briantuju Can you share the full error output please?

**Comment by nunomaduro** [comment]
Please try with the latest version of Forge CLI, and let me know how it goes.
