### ISSUE TITLE
An unexpected error occured - no error message

### ISSUE THREAD

**Issue by chris-ware** [laravel/forge-cli#55]
An unexpected error occured. Please report this issue here:  
https://github.com/laravel/forge-cli/issues/new/choose       
  
- Forge CLI Version: 1.4.0                                   
- PHP Version: 8.1.3                                         
- Operating System: Darwin                                   
- Error Message: .    
- Running on an M1 pro macbook

### Description:

I don't actually know what caused it to error. Standard forge setup, just doing a deploy and it threw this error with no error message. Fully understand if you'd like to just close this issue, due to lack of information, but I wanted to report it, just in case its useful.

### Steps To Reproduce:

forge deploy {site}

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
