### ISSUE TITLE
Intermittent SSH connectivity issues & command inconsistencies

### ISSUE THREAD

**Issue by agroebe** [laravel/forge-cli#61]
- Forge CLI Version: 1.4.0
- PHP Version: 8.0.10

### Description:
I'm getting a lot of intermittent SSH connectivity issues and some of the commands do not seem to be working properly, maybe as a result of the SSH issues.

SSH issues first:
I am following the Forge CLI docs and have made sure to configure my SSH keys, and I have verified that they are indeed on the server.

I run `ssh:test` once, which seems to work. But then I run the command 30 seconds later and it now claims I do not have SSH keys configured:
https://i.imgur.com/UWKRRPV.png
This has been happening for hours ever since I downloaded Forge CLI.

In addition, most of the commands are not working properly, I assume because of the connectivity issues:
https://i.imgur.com/Db8uYd7.png
This is one example, using the `site:logs` command, but the same inconsistencies can be seen with the 'site:deploy' command, basically anything that I imagine requires an SSH.

### Steps To Reproduce:
Unfortunately I am not able to provide reproduceable steps as this seems to be some weird ephemeral bug that nobody else is able to really help with.

**Comment by driesvints** [comment]
Hi @agroebe, can you send this to Forge support instead?
