### ISSUE TITLE
Command output out of sync - returning previous command

### ISSUE THREAD

**Issue by valorin** [laravel/forge-cli#65]
- Forge CLI Version: Forge CLI 1.4.0
- PHP Version: 8.1.12

### Description:

Somehow running commands via the Forge CLI got out of sync with the results from the server, and as such every subsequent command returns the output from the previous command. The output looks fine when viewing commands on the Forge website, it's only the commands through the CLI.

I'm guessing it's running the command and then returning the last command execution output, and somehow one of the previous commands failed, causing it to have the previous command output in the queue to be returned. It seems to be a problem somewhere on Forge's side. I can't see any local directory on my system or the servers that contain the output, and it is affecting all of my servers that I've tested with.

### Steps To Reproduce:

I don't know what caused it, but you can see it in action here:

```
valorin@Eowyn:~/dev/wevsite (main * u=)$ forge command withextraveg.net --command="php artisan env"
==> Queuing Command
==> Waiting For Command To Run
==> Running


  Event unresolvable.


valorin@Eowyn:~/dev/wevsite (main * u=)$ forge command withextraveg.net --command="php artisan env"
==> Queuing Command
==> Waiting For Command To Run
==> Running

  ▕ Current application environment: production

==> Command Run Successfully.
valorin@Eowyn:~/dev/wevsite (main * u=)$ forge command withextraveg.net --command="php artisan list"
==> Queuing Command
==> Waiting For Command To Run
==> Running

  ▕ Current application environment: production

==> Command Run Successfully.
```

Note that I ran the `artisan env` command twice, and the initial time it failed, with the two subsequent command executions returning the output from `artisan env`, with the output from `artisan list` not being displayed.

**Comment by nunomaduro** [comment]
This issue is now fixed. Can you try again?

**Comment by valorin** [comment]
Yep, it seems to be working now. Thanks! 😁
