### ISSUE TITLE
Error when entering `exit` on the server

### ISSUE THREAD

**Issue by nikolaynizruhin** [laravel/forge-cli#68]
- Forge CLI Version: 1.4.0
- PHP Version: 8.2.0
- Operating System: Darwin
- Error Message: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in phar:///Users/mykolanizriukhin/.composer/vendor/laravel/forge-cli/builds/forge/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98.

### Description:
Got an error while exiting the server

### Steps To Reproduce:
Enter `exit` when logged into the server

**Comment by driesvints** [comment]
I released v1.4.1 with an update for Carbon that should fix this.

**Comment by nikolaynizruhin** [comment]
Cool! Thank you!
