### ISSUE TITLE
Warning message following any command on fresh install (but all seems to be working)

### ISSUE THREAD

**Issue by Nathanjms** [laravel/forge-cli#69]
- Forge CLI Version: 1.4.0
- PHP Version: 8.2.0
- Operating System: Darwin (MacBook M2)
- Error Message: Carbon\Carbon::setLastErrors(): Argument `#1` ($lastErrors) must be of type array, bool given, called in phar:///Users/nathanjames/.composer/vendor/laravel/
  forge-cli/builds/forge/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98.

### Description:

After each command, I am receiving the error message above. The actual commands all seem to be working as expected (eg. I can run `forge ssh` and get onto the server correctly, but they all show the below after running:

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/64075030/207281592-073df570-9aa3-435b-817f-0802e694e39b.png">

When running `forge -h`, the error message does not display.

This was the first use of composer on this machine, if that has any relevance.

There's a high chance this is something specific to my machine, but thought it'd be better to report just in case.

### Update:

**I've downgraded to php8.1 and the error has dissapeared - so it's definitely an issue with php8.2 compatability**

### Steps To Reproduce:

- Install PHP 8.2
- Install composer
- Install forge

Following this, running even just `forge` gives this error, as well as running any `forge` command (e.g. `forge server:current` and `forge ssh`).

**Comment by driesvints** [comment]
I released v1.4.1 with an update for Carbon that should fix this.

**Comment by Nathanjms** [comment]
> I released v1.4.1 with an update for Carbon that should fix this.

I updated to v1.4.1 and switched back to php 8.2.0, and can confirm it's no longer showing the error, thanks.
