### ISSUE TITLE
Login fails with 

### ISSUE THREAD

**Issue by clh-code** [laravel/forge-cli#74]
### Forge CLI Version

1.7.0

### PHP Version

8.2.0

### Description

I downloaded the latest version of Forge CLI.

I ran the command: `forge login`

Responds: `Please Enter Your Forge API Token:`

I enter my token that I get from: https://forge.laravel.com/user-profile/api

This following message shows:

`
An unexpected error occured. Please report this issue here:                                                  
  https://github.com/laravel/forge-cli/issues/new/choose                                                       
                                                                                                               
  - Forge CLI Version: 1.7.0                                                                                   
  - PHP Version: 8.2.0                                                                                         
  - Operating System: WINNT                                                                                    
  - Error Message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https   
  ://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://forge.laravel.com/api/v1/servers.
`

### Steps To Reproduce

Get API key from: https://forge.laravel.com/user-profile/api

Download latest version of Forge CLI.

Run command: `forge login`

Enter API key.

**Comment by nunomaduro** [comment]
Occasionally, we've observed this problem occurring when users are connected to a public network or utilize certain DNS servers. Could you attempt using Google Public DNS instead? The IP addresses for Google Public DNS (IPv4) are as follows:

- 8.8.8.8
- 8.8.4.4
