### ISSUE TITLE
v1.8 (v1.7?) breaks PHP 8.0 support

### ISSUE THREAD

**Issue by lasseeee** [laravel/forge-cli#76]
### Forge CLI Version

1.8.0

### PHP Version

8.0.28

### Description

Latest minor version removed support for php 8.0:

```
laravel/forge-cli[v1.7.0, ..., v1.8.0] require php ^8.1.0 -> your php version (8.0.28) does not satisfy that requirement.
```

I would consider this a braking change and to either bump major version number og fix braking change.

### Steps To Reproduce

Try installing globally through Composer on any setup with php 8.0 installed.

**Comment by nunomaduro** [comment]
Thank you for reporting this issue. There is no breaking change, as existing Forge CLI PHP 8.0 users will get updates up to the version 1.7.

Regarding the change, we simply don't support PHP 8.0 anymore. Sorry!
