### ISSUE TITLE
Login Token problem

### ISSUE THREAD

**Issue by LukasCCB** [laravel/forge-cli#77]
### Forge CLI Version

1.0.8

### PHP Version

8.2.7

### Description

After put 
forge login
later put TOKEN, give this error

 An unexpected error occured. Please report this issue here:
  https://github.com/laravel/forge-cli/issues/new/choose

  - Forge CLI Version: 1.8.0
  - PHP Version: 8.2.7
  - Operating System: WINNT
  - Error Message: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://fo
  rge.laravel.com/api/v1/servers.

### Steps To Reproduce

forge login
> TOKEN

**Comment by crynobone** [comment]
It seem you missing correct SSL certificate locally and this prevents the CLI client from communicating to Forge API, you need to fix your local PHP using similar solution to https://stackoverflow.com/a/34883260
