### ISSUE TITLE
array_map() Error with Forge CLI 1.8.0 on Darwin OS

### ISSUE THREAD

**Issue by IbrahimAlshekh** [laravel/forge-cli#80]
### Forge CLI Version

1.8.0

### PHP Version

8.2.9

### Description

Encountered an `array_map()` error in Forge CLI version 1.8.0 when trying to deploy a website using the `forge deploy` command.

### Environment
- **Forge CLI Version**: 1.8.0
- **PHP Version**: 8.2.9
- **Operating System**: Darwin

### Expected Behavior
Expected the website to deploy without errors.

### Actual Behavior
Received an error message stating:
```
array_map(): Argument #2 ($array) must be of type array, string given.
```

### Additional Information
The issue appears consistently when attempting to deploy using the `forge deploy` command.

### Error Message
![image](https://github.com/laravel/forge-cli/assets/38472411/e8fe0c2b-76a7-4be5-adae-de93e568d44b)

### Steps To Reproduce

1. Run the command `forge deploy [WEBSITE_NAME]` to deploy a website.
2. Encounter the `array_map()` error.

**Comment by IbrahimAlshekh** [comment]
### Steps to Reproduce
1. Execute the command `forge server:switch`.
2. Select the desired server from the list using the UP arrow key on the keyboard.
3. Run the command `forge deploy`.
4. Select the appropriate site for deployment using the UP arrow key.
5. Encounter one of the two error messages: 

 either:
<img width="1089" alt="image" src="https://github.com/laravel/forge-cli/assets/38472411/2318884f-9541-45df-ac52-f5694f0959fa">

or:
<img width="758" alt="image" src="https://github.com/laravel/forge-cli/assets/38472411/58b86a48-cafc-4f9b-896f-e5eb53f6970d">


### Additional Information
- The issue is consistent and occurs every time the `forge deploy` command is run for the first time after using `forge server:switch`.
- The problem does not seem to affect the deployment process itself, as the site still deploys successfully.
- The errors do not occur in subsequent `forge deploy` commands after the first run.

**Comment by jbrooksuk** [comment]
So far, I've not been able to replicate this issue. I can switch servers and deploy without any exceptions.

**Comment by jbrooksuk** [comment]
@IbrahimAlshekh quick question, are you the owner of both servers?

**Comment by jbrooksuk** [comment]
@IbrahimAlshekh thanks for confirming. I'm still unable to replicate this issue or see what may be causing it. Assigned to @nunomaduro to check in here.

**Comment by nunomaduro** [comment]
Hi @IbrahimAlshekh, I will need access to your account information, to able to replicate this issue locally. Please reach out our support at `forge@laravel.com`, and reference this issue on the support ticket. We will take it from there.

**Comment by JonErickson** [comment]
Did we find a resolution? Just encountered this in my CI pipeline as well.
