### ISSUE TITLE
Lack of Option to Disconnect Envoyer Projects in Laravel Forge

### ISSUE THREAD

**Issue by mauriciodulce** [laravel/forge-cli#81]
### Forge CLI Version

1.8.0

### PHP Version

8.1.26

### Description

In the recent integration between Laravel Forge and Envoyer, I've encountered a significant limitation. Once a site is connected with Envoyer through Forge, there's no provided option in the user interface or the Laravel Forge API to disconnect that project from Envoyer.

### Steps To Reproduce

**Steps to Reproduce:**

1. Connect a project from Laravel Forge with Envoyer.
2. Look for the option to disconnect the project from Envoyer within the Laravel Forge interface or through the API.
3. Note the absence of any function or button to perform this action.

**Expected Outcome:**

An explicit option should be available to disconnect a project from Envoyer within the Laravel Forge interface or through its API. This functionality is crucial to provide a complete experience and allow for full management of the connection between these services.

**Impact:**

The lack of this option makes it difficult for users to handle connections between Forge and Envoyer in a complete and efficient manner. This missing functionality can be critical for projects needing adjustments in their integrations or temporary disconnections.

**Additional Information:**

This issue limits users' flexibility and control over their integrations between Laravel Forge and Envoyer. Adding a feature to disconnect projects would be beneficial for those needing to adjust their configurations or make changes in the connection between both platforms.

**Comment by jbrooksuk** [comment]
We don't currently have the ability to do this in the frontend or API.

It's something that's on our list though 👍🏻

**Comment by mauriciodulce** [comment]
@jbrooksuk Why are you closing this if it's not yet resolved? It seems like common sense isn't a priority in Forge because if an integration is enabled, there should also be an option to disconnect projects. Right now, I'm talking to someone named Guus who's asking me for the IDs of the sites, when I'm asking to disconnect all the Envoyer sites. I decided to use Buddy and request a refund from Envoyer because Envoyer doesn't allow me to manage a project and multiple environments. In other words, for each environment, I have to create a new project, and I'm still waiting for the Envoyer refund.
