### ISSUE TITLE
Lack of Option to Disconnect Envoyer Projects in Laravel Forge

### ISSUE THREAD

**Issue by mauriciodulce** [laravel/forge-cli#82]
### Forge CLI Version

1.8.0

### PHP Version

8.1.26

### Description

In the recent integration between Laravel Forge and Envoyer, I've encountered a significant limitation. Once a site is connected with Envoyer through Forge, there's no provided option in the user interface or the Laravel Forge API to disconnect that project from Envoyer.

### Steps To Reproduce

1. Connect a project from Laravel Forge with Envoyer.
2. Look for the option to disconnect the project from Envoyer within the Laravel Forge interface or through the API.
3. Note the absence of any function or button to perform this action.

**Expected Outcome:**

An explicit option should be available to disconnect a project from Envoyer within the Laravel Forge interface or through its API. This functionality is crucial to provide a complete experience and allow for full management of the connection between these services.

**Impact:**

The lack of this option makes it difficult for users to handle connections between Forge and Envoyer in a complete and efficient manner. This missing functionality can be critical for projects needing adjustments in their integrations or temporary disconnections.

**Additional Information:**

This issue limits users' flexibility and control over their integrations between Laravel Forge and Envoyer. Adding a feature to disconnect projects would be beneficial for those needing to adjust their configurations or make changes in the connection between both platforms.

**Comment by driesvints** [comment]
Hi there. We've taken your suggestion into consideration, thanks.
