### ISSUE TITLE
Can't push environment file

### ISSUE THREAD

**Issue by Tachii** [laravel/forge-cli#85]
### Forge CLI Version

1.8.0

### PHP Version

 8.3.1 

### Description

forge env:push api.signalspot.io .env.production
==> Uploading [.env.production] Environment File

                                                               
  An unexpected error occured. Please report this issue here:  
  https://github.com/laravel/forge-cli/issues/new/choose       
                                                               
  - Forge CLI Version: 1.8.0                                   
  - PHP Version: 8.3.1                                         
  - Operating System: Darwin                                   
  - Error Message: {                                           
      "message": "Server Error"                                
  }.                                                           

### Steps To Reproduce

Just trying to push env file

**Comment by driesvints** [comment]
Hi @Tachii. Could you please email Forge support? Thanks
