### ISSUE TITLE
Forge login successful but the token is not saved.

### ISSUE THREAD

**Issue by adampatterson** [laravel/forge-cli#86]
### Forge CLI Version

1.8.0

### PHP Version

8.2.15

### Description

Authentication works, but commands after auth are forbidden 

### Steps To Reproduce

When running `forge login` and am greeted with `==> Authenticated Successfully As email@domain.com`

I then ran `forge site:list` and get Forbidden.

![image](https://github.com/beyondcode/forge-cli/assets/31537/b7981436-21dc-418c-a752-452d10640e88)

**Comment by jbrooksuk** [comment]
@adampatterson are you seeing the same error for all commands?

**Comment by adampatterson** [comment]
@jbrooksuk I was going to say yes but then I tried `forge server:list` and it worked and that got me looking at `server:switch`

After running the command with an ID it was able to run `ssh:test`

It was also a bit more confusing when I ended up on the the BeyondCo site and sat `forge init` and the steps about the token being saved in a YAML file.

I think everything is actually fine, user error 😭
