### ISSUE TITLE
[DEPLOY] strpos(): Empty needle In RemoteRepository.php line 121

### ISSUE THREAD

**Issue by modernben** [laravel/forge-cli#9]
OS: Mac 11.5.1 (Intel)
CLI Version: 0.1.2
PHP Version: 7.4
Target server PHP version: 7.4
Command: `forge deploy` (interactively)

Steps:
Run command
Typed out site id from list
Saw Queueing, Waiting, and Deploying.

Received:
strpos(): Empty needle in RemoteRepository.php line 121

Expected:
Deploy steps and a success

FWIW, the deploy finished/completed on the server.

![Screen Shot 2021-08-02 at 8 07 41 PM](https://user-images.githubusercontent.com/67608755/127951512-812169d2-9ad4-4a59-bb96-bc1bc8b1f3de.png)

**Comment by nunomaduro** [comment]
Fixed on `v0.1.3`.
