### ISSUE TITLE
Deploy bug

### ISSUE THREAD

**Issue by gfirem** [laravel/forge-cli#94]
### Forge CLI Version

1.8.3

### PHP Version

8.3.12

### Description

  - Forge CLI Version: 1.8.3                                   
  - PHP Version: 8.3.12                                        
  - Operating System: Darwin                                   
  - **Error Message**: Trying to access array offset on null.

### Steps To Reproduce

Just deploy using the forge command line

**Comment by jbrooksuk** [comment]
Can you provide us with a full stack trace, please.

**Comment by gfirem** [comment]
What do you mean with the full stack trace? 

I shared what the command line throws.

**Comment by jbrooksuk** [comment]
@gfirem is there no additional data like like numbers?

**Comment by gfirem** [comment]
No, just that

<img width="505" alt="image" src="https://github.com/user-attachments/assets/8fe804d6-744f-4a79-ae2f-3bd1e694b71d">

**Comment by gfirem** [comment]
Hello, any update on this? How does priority support work on Forge if this 2 days old?

**Comment by gfirem** [comment]
this looks related https://github.com/PHPOffice/PhpSpreadsheet/issues/2315

**Comment by gfirem** [comment]
This was closed with no solution @jbrooksuk

**Comment by gfirem** [comment]
I was able to sort out this issue. I'm new to using Forge, but the problem looks like it was in the service because the server has an empty site, and deployment still needs to be done. I force a deployment with no composer install using the admin, and after it, I trigger the deploy from cmd, and it works. 

**It would be nice if the support is better for a paying service.**
